[project]
name = "pozorni-translater"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "coqui-tts>=0.24.3",
    "dearpygui>=2.0.0",
    "googletrans>=4.0.2",
    "pyaudio>=0.2.14",
    "speechrecognition>=3.14.1",
]
